# Generated by Django 5.2.17 on 2026-10-02 15:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', "Phone must be 9-15 digits, optionally starting with '+'.")])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('district', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('risk_status', models.CharField(choices=[('pending', 'Pending'), ('clear', 'Clear'), ('flagged', 'Flagged (recently cleared land)'), ('check_failed', 'Check failed (registry unreachable)')], db_index=True, default='pending', max_length=16)),
                ('risk_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='core.farmer')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='core.sector')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grade'],
                'constraints': [models.UniqueConstraint(fields=('season', 'grade'), name='unique_price_per_season_grade')],
            },
        ),
        migrations.CreateModel(
            name='RiskCheckAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(help_text='1-based, within one check round')),
                ('outcome', models.CharField(choices=[('clear', 'Clear'), ('flagged', 'Flagged'), ('error', 'Error')], max_length=8)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_attempts', to='core.plot')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WashingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='core.sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='plot',
            name='washing_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='core.washingstation'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('5000'))])),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1)),
                ('delivered_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('plot_risk_status', models.CharField(choices=[('pending', 'Pending'), ('clear', 'Clear'), ('flagged', 'Flagged (recently cleared land)'), ('check_failed', 'Check failed (registry unreachable)')], max_length=16)),
                ('client_ref', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.plot')),
                ('washing_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.washingstation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('farmer', 'name'), name='unique_plot_name_per_farmer'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['washing_station', '-id'], name='core_delive_washing_906be1_idx'),
        ),
    ]
