# Generated by Django 5.2.17 on 2026-10-04 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('field_agent', 'Field agent'), ('exporter_partner', 'Exporter partner'), ('compliance_auditor', 'Compliance auditor')], max_length=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('washing_station', models.ForeignKey(blank=True, help_text='Required for field_agent; the station this agent is scoped to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_agents', to='core.washingstation')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Role at the time of access (roles can change later).', max_length=24)),
                ('action', models.CharField(choices=[('view_plot_coordinates', 'Viewed plot coordinates'), ('view_farmer_identity', 'Viewed farmer identity data')], max_length=32)),
                ('precision', models.CharField(max_length=20)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', '-id'], name='core_access_user_id_f48ffa_idx'), models.Index(fields=['action', '-id'], name='core_access_action_3c3e00_idx')],
            },
        ),
    ]
