# Generated by Django 5.2.17 on 2026-10-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farmer_national_id_userprofile_accesslogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='cooperative',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='member_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='plot_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
